version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: {{ domainedb }}:{{ portdb }}
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: {{  mdpdb  }} 
      WORDPRESS_DB_NAME: mydatabase
    volumes:
      - ./:/var/www/html