---
- name: Install and configure NFS Server
  hosts: front
  tasks:
    - name: Install NFS Server packages
      apt:
        name:
          - nfs-kernel-server
          - nfs-common
        state: present
    - name: Start NFS Server service
      service:
        name: nfs-kernel-server
        state: started
    - name: Create wordpress-data directory
      file:
        path: /home/wordpress-data
        state: directory
    - name: Update exports file
      lineinfile:
        path: /etc/exports
        line: "/home/wordpress-data/ 192.168.16.0/255.255.255.0(rw,no_root_squash,anonuid=1000,anongid=1000,sync)"
        state: present
    - name: Restart NFS Server
      service:
        name: nfs-kernel-server
        state: restarted

- name: Mount NFS share on backend hosts
  hosts: backend3
  tasks:
    - name: Install NFS client
      apt:
        name: nfs-common
        state: present
    - name: Create mount point
      file:
        path: /home/wordpress-data
        state: directory
    - name: Mount NFS share
      mount:
        path: /home/wordpress-data
        src: "{{ hostvars[inventory_hostname]['IpPrive'] }}:/home/wordpress-data"
        fstype: nfs
        state: mounted
